[General]
__userfile__=true
icon_size=32
panel_size=48
panels=panel1
preferred_backend=labwc:wlroots

[mainmenu]
alignment=Left
type=mainmenu

[desktopswitch]
alignment=Left
rows=1
showcurrent=true
showicons=false
showlabels=true
type=desktopswitch

[taskbar]
alignment=Left
type=taskbar

[statusnotifier]
alignment=Right
showall=false
showmenu=true
type=statusnotifier

[volume]
alignment=Right
device=0
mixer=pavucontrol
showlabel=false
type=volume
volumestep=5

[worldclock]
alignment=Right
format=ddd MMM d HH:mm
showdate=true
showtime=true
timezone=UTC
tooltipformat=LLLL
type=worldclock

[showdesktop]
alignment=Right
type=showdesktop

[spacer]
alignment=Left
expand=true
type=spacer
width=0

[panel1]
alignment=0
animation-duration=0
animations=true
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font=Noto Sans, 10, -1, 5, 50, 0, 0, 0, 0, 0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
height=48
hidable=false
hide-on-overlap=false
iconSize=22
iconsize=22
lineCount=1
linecount=1
lockPanel=false
lockpanel=false
marginbottom=0
marginleft=0
marginright=0
opacity=90
panelSize=32
panelsize=32
plugins=mainmenu, desktopswitch, taskbar, spacer, statusnotifier, volume, worldclock, showdesktop
position=Top
reserve-space=true
show-delay=0
visible-margin=true
width=100
width-percent=true
